# estrutura base de um script de pipeline:

 

# [script de pipeline] -> YAML (Github Actions, Azure Devops, CircleCI, GitlabCI, etc.) 
#   [declaracoes]
#     [config do so] (windows/linux/mac, chrome/firefox/edge, ...) 
#     [deps do projeto] (node/npm, java/maven,gradle, python/pip, ...)
#     [variaveis] (variáveis de ambiente, chaves de acesso a plataformas, etc.)
#     [projetos] (aplicacoes, projeto de teste, etc.)
#     [acoes ou passos]


name: CI Mentoria e2e

on: 
  workflow_dispatch: 

jobs:
     tests:

    # [config do so] (Windos/linux/mac, chrome/firefox/edge...]
      runs-on: ubuntu-latest

    # [variaveis] (variáveis de ambiente, chaves de acesso a plataformas, etc.)
      env: 
       API_BASE_URL: 'http://localhost:3000'
       PORT: 4000

    # [acoes ou passos]
      steps: 
        # [projetos] (aplicacoes, projeto de teste, etc.)
        - name: Checkout do Repositório
          uses: actions/checkout@v4

        - name: Instalando as dependências
          run: npm install
        
        - name: Iniciar o servidor de mocks
          run: npm run mock-server &
        
        - name: Iniciar o servidor de aplicacao
          run: npm run server &

        - name: Executar os testes
          run: npx cypress run 
        
